export const OPEN_MODAL_NEW_ROOM = 'OPEN_MODAL_NEW_ROOM';
export const CLOSE_MODAL_NEW_ROOM = 'CLOSE_MODAL_NEW_ROOM';
export const CREATE_NEW_ROOM_START = 'CREATE_NEW_ROOM_START';
export const CREATE_NEW_ROOM = 'CREATE_NEW_ROOM';
